packages:
  - packages/*
  - apps/*

allowBuilds:
  '@google/genai': false
  '@parcel/watcher': true
  protobufjs: false
  vue-demi: true

catalog:
  '@types/node': ^26.4.0
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
  typescript: 7.0.2
  '@oxc-node/cli': ^0.1.0

minimumReleaseAgeExclude:
  - '@cieljs/instrument@0.0.1'

overrides:
  '@vue/compat': 3.6.0-rc.4
  '@vue/compiler-core': 3.6.0-rc.4
  '@vue/compiler-dom': 3.6.0-rc.4
  '@vue/compiler-sfc': 3.6.0-rc.4
  '@vue/compiler-ssr': 3.6.0-rc.4
  '@vue/compiler-vapor': 3.6.0-rc.4
  '@vue/reactivity': 3.6.0-rc.4
  '@vue/runtime-core': 3.6.0-rc.4
  '@vue/runtime-dom': 3.6.0-rc.4
  '@vue/runtime-vapor': 3.6.0-rc.4
  '@vue/server-renderer': 3.6.0-rc.4
  '@vue/shared': 3.6.0-rc.4
  typescript: npm:typescript-native-bridge@6.0.3-bridge.15.tsgo.7.0.2
  vite: 'catalog:'
  vue: 3.6.0-rc.4

peerDependencyRules:
  allowedVersions:
    vite: 0.2.9
